version: "3"
services:
  postgres:
    build: ./postgres
    restart: always
#    ports:
#      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jobrunr

# this is the dashboard. We start it first so that it can create all the tables correctly
  springboot-jobrunr-dashboard:
    image: app.jar
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/jobrunr?useSSL=false"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      ORG_JOBRUNR_DATABASE_SKIP_CREATE: "false"
      ORG_JOBRUNR_DATABASE_TABLE_PREFIX: "demo"
      ORG_JOBRUNR_JOB-SCHEDULER_EBABLED: "true"
      ORG_JOBRUNR_BACKGROUND_JOB_SERVER_ENABLED: "false"
      ORG_JOBRUNR_DASHBOARD_ENABLED: "true"
      ORG_JOBRUNR_BACKGROUND_JOB_SERVER_PERMANENTLY_DELETE_DELETEDJOBS_AFTER: "1"

    ports:
      - "8000:8000"
      - "8080:8080"
    build:
      context: .
      dockerfile: "Dockerfile"
    depends_on:
      - postgres

# this is the background job server. It depends on the dashboard so that it does not try to create the tables twice.
# We can scale this using docker compose up --scale springboot-backend=3
  springboot-backend:
    image: app.jar
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/jobrunr?useSSL=false"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      ORG_JOBRUNR_DATABASE_SKIP_CREATE: "false"
      ORG_JOBRUNR_DATABASE_TABLE_PREFIX: "demo"
      ORG_JOBRUNR_JOB-SCHEDULER_EBABLED: "false"
      ORG_JOBRUNR_BACKGROUND_JOB_SERVER_ENABLED: "true"
      ORG_JOBRUNR_BACKGROUND_JOB_SERVER_PERMANENTLY_DELETE_DELETEDJOBS_AFTER: "1"
    build:
      context: .
      dockerfile: "Dockerfile"
    depends_on:
      - postgres
      - springboot-jobrunr-dashboard

networks:
  default:
    driver: bridge
